# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            INSTRUCTION SET
tagline:          'assembling new programmers'
description:      'A blog by the instructors of <a href="https://generalassemb.ly/">General Assembly&apos;s</a> <a href="https://generalassemb.ly/education/web-development-immersive">Web Development Immersive</a>.'
url:              "https://generalassemb.ly/education/web-development-immersive#instructors"
paginate:         5

author:
  name:           'GA Instructors'
  url:            https://github.com/ga-instructors

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/ga-instructors

source:           _source
destination:      _site
